### ISSUE TITLE
Namecheap doesn't open with blocklists on

### ISSUE THREAD

**Issue by mystic-githuber** [mullvad/dns-blocklists#115]
Namecheap.com doesn't open with blocklists on

**Comment by oskaralmlov** [comment]
This seems to be due to a false-positive in the upstream oisd-nsfw list. It has been resolved in the upstream list but the changes have not been pulled down to this repository. I expect this to happen within the following days.

Relevent upsteam commit: https://github.com/sjhgvr/oisd/commit/94d9a98f6a3b05c286586e056889d14a8a8952b2

**Comment by jbjorkang** [comment]
This has been updated as of: https://github.com/mullvad/dns-blocklists/commit/98d501ef8f1da76db2ab799c0873e3cfe9ae2c71
