### ISSUE TITLE
"www.sedaily.com" is blocked

### ISSUE THREAD

**Issue by Hystrike** [mullvad/dns-blocklists#117]
Domain name: https://www.sedaily.com/
It's just a news media site, but it's blocked by base.dns.mullvad.net(DNS_PROBE_FINISHED_NXDOMAIN).

**Comment by oskaralmlov** [comment]
Hi, 

We don't block this domain but rather it's the nameservers that are responsible for sedaily.com that are blocking _some_ of our servers that provide the encrypted dns service. Unfortunately there isn't anything that we can do about this.

Our servers in Sweden, Frankfurt and Singapore are blocked from resolving this domain. So if you are using our VPN service you can try selecting a VPN relay that isn't close to these servers so that your traffic will be routed to a different dns server that isn't blocked.

Best of luck!
