### ISSUE TITLE
Achievements not working in Apple "Game Center"

### ISSUE THREAD

**Issue by notDavid** [mullvad/dns-blocklists#123]
Hi there, as the title says, it's impossible to:

- See any Achievement details (they are possibly cached on your device... so you sometimes might see them anyway)
- Complete any Achievement while playing an AppStore game
- Opening my Achievements in the macOS AppStore app, shows an error: `Unable to load data due to network connectivity issues or errors`

while DNS blocking is active the Mullvad VPN app.

The responsible domain causing the issue seems to be: `stats.gc.apple.com`.

Disabling the Dns content blockers fixes the issue. This is reproducible.

**Comment by jbjorkang** [comment]
This URL falls under the category of privacy, or rather tracking. 

In general the point of the DNS block lists is to make browsing the Internet less frustrating, but primarily to block unwanted trackers, websites and hidden anti-privacy content.

In this instance there are three options:

1. You disable the trackers option locally.
2. We modify the block lists for each of these individual requests.
3. We do nothing, and accept that portions of the web will break because they do not adhere to privacy respecting methods.

In general I personally have been quite lax about option 2, as in some cases there are some websites that just should not be blocked, as they were added by mistake.

In this case I believe that you are subject to case 3, where it does as is intended, and is blocking trackers and behaving in an anti-privacy.

**Comment by jbjorkang** [comment]
> @jbjorkang Thank you for your reply;
> 
> Are you aware it's (frustratingly) breaking a functionality people are paying for (Apple Arcade Subscription) ?

I completely understand, perhaps the better angle would be to put pressure on the developers so that they do not gather and track their users instead?

**Comment by hagezi** [comment]
Just a note, the domain is not used for "classic user tracking". It is only used for achievement "tracking" in the Game Center. Blocking breaks the game centre achievement page and more.

That is why there are not many blocklists in which the domain is blocked:

```
Blocklists:
 - 1Hosts.Lite     OK
 - 1Hosts.Mini     OK
 - 1Hosts.Pro      OK
 - AdGuardDNS      OK
 - AhaDNS          OK
 - CONTROLD.AT     OK
 - DevDansHosts    BLOCKED
 - EasyList        OK
 - GoodbyeAds      OK
 - HaGeZi.LIGHT    OK
 - HaGeZi.NORMAL   OK
 - HaGeZi.PRO      OK
 - HaGeZi.PRO.PLUS OK
 - HaGeZi.TIF      OK
 - HaGeZi.ULTIMATE OK
 - hBlock          OK
 - NextDNS         OK
 - OISD.Big        OK
 - OISD.Small      OK
 - QuidsUp.NOTRACK BLOCKED
 - StevenBlack     OK

```

**Comment by jbjorkang** [comment]
I just investigated where we pull that from, and realise that the URL is from a private no longer updated list.

I will remove that list as it is not good to keep something never updated.

My mistake, thanks for reporting. The list will be updated on Monday again.

**Comment by hagezi** [comment]
@notDavid 

The list is generated by a custom script on my build system. You can also check domains yourself, e.g. via https://rethinkdns.com/search

**Comment by jbjorkang** [comment]
> @jbjorkang Any idea when we can expect this to be live in the [Mullvad VPN](https://github.com/mullvad/mullvadvpn-app/) app?

I pushed the update yesterday. It should be live now, our block lists typically update daily server side. 

Today or tomorrow.

**Comment by jbjorkang** [comment]
I will look as soon as I can
