### ISSUE TITLE
Startpage anonymous view bypass adult/porn blocking

### ISSUE THREAD

**Issue by anxiouslelimo** [mullvad/dns-blocklists#124]
Startpage anonymous view bypass adult/porn blocking

**Comment by oskaralmlov** [comment]
Hi. 

We can't inspect the content being shown on screen, just the hostnames being resolved while using the service. 
As these hostnames aren't used _just_ for accessing pornography but rather as a general anonymous view it's not something that we will add. We wouldn't want someone to be blocked from using the anonymous view completely just because they want to block pornography.
