### ISSUE TITLE
*.ingest.sentry.io not blocked on anti-tracker dns endpoints

### ISSUE THREAD

**Issue by surfaceflinger** [mullvad/dns-blocklists#132]
### Have you contacted the Support Team already?

- [X] I have attempted already, but to no avail, or they pointed me here.

### What are the issues you need support with?

Sentry is quite a common tracker yet for some reason it's not blocked here.

```
nat@blahaj [~] ✨ doggo 2b19802000444b71b53899a26418c0ef@o923049.ingest.sentry.io @https://all.dns.mullvad.net/dns-query
NAME                                                       	TYPE	CLASS	TTL 	ADDRESS       	NAMESERVER                            
2b19802000444b71b53899a26418c0ef\@o923049.ingest.sentry.io.	A   	IN   	293s	34.120.195.249	https://all.dns.mullvad.net/dns-query	
nat@blahaj [~] ✨ doggo 2b19802000444b71b53899a26418c0ef@o923049.ingest.sentry.io @https://base.dns.mullvad.net/dns-query
NAME                                                       	TYPE	CLASS	TTL 	ADDRESS       	NAMESERVER                             
2b19802000444b71b53899a26418c0ef\@o923049.ingest.sentry.io.	A   	IN   	300s	34.120.195.249	https://base.dns.mullvad.net/dns-query	

```

### Additional Information

Worth noting that of course everything under ingest should be blocked

**Comment by oskaralmlov** [comment]
Hi,
Sorry it has taken us so very long to respond to your request. I don't know why this hasn't been addressed earlier.

I've looked into this and it seems like this has previously been [added and subsequently removed](https://github.com/easylist/easylist/issues/6963) from one of our upstream lists (Easylist Privacy) because it broke so many things for people. 

We trust the judgement of the list curators here so I will not be adding a manual override for this specific domain to our repository. If you disagree with this I recommend that you try getting the change reverted in the upstream list.

Again, sorry it took us so long.
