### ISSUE TITLE
Chinese social media sites weibo and sina are being blocked

### ISSUE THREAD

**Issue by slammpete** [mullvad/dns-blocklists#86]
do you have a dns server that blocks nothing? I am unable to reach the two biggest social media sites in china when using mullvad. When mullvad is disabled, i can  reach them fine.

Please provide a dns that blocks nothing. no adware, malicious sites, etc... thanks.

**Comment by jbjorkang** [comment]
All our VPN servers run their own DNS resolvers that do not block anything by default. Try using our service without any toggles set, or without using any custom DNS IPs.

**Comment by slammpete** [comment]
yes when i turn off your app and use my providers DNS IP's i am able to reach the site with no problem. In your app, when i connect to certain servers i am able to use weibo but the latency is so high since i am in south america the only one that works well is miami, florda. if i switch to japan or anywhere in asia everything works fine. for now i have created a new firefox profile that uses my providers dns ip's instead of yours because your app lets me tunnel an app but not with an particular instance of an app since i have many firefox browsers running with different setups.

**Comment by slammpete** [comment]
yes i tried this also. default setting on your app with no modifications
and using the default dns servers.

unfortunately i am also noticing more and more sites are blocking your
ip's. maybe it's due to a bigger more users using mullvad now. this also
happened when i was using another vpn that just opened but after a year or
two the user base grea a lot and their ip's stopped working.

**Comment by slammpete** [comment]
ok this is great thanks for looking into this. you can disregard my
previous message.

yes the chinese social media sites regularly change who they allow to use
their sites so it's not just your DNS servers. I am not sure why or when
they do this but it is a pain. Usually i use your hong kong server to
access the site then but they even blocked that one also, probably due to
the unrest between the two.

**Comment by slammpete** [comment]
sorry one last question, if use another dns server like what some redditors
suggested, doesn't that then make my traffic visible to my isp? so for
example i changed one instance of firefox to use cloudfare and ran your
command line to see if all was ok and it says i am "leaking dns"
information. Does this mean now my isp can only see which sites i am
visiting but not the traffic since i am still routing through our vpn?

**Comment by slammpete** [comment]
i do not have the mrt command in my bin and does not work. i am on arch
linux.

**Comment by slammpete** [comment]
Sorry I thought you worked for mullvad. I really appreciate you taking the
time to write this script and all the help you provided.

I feel  a bit guilty because i have been coding for many many years but I
offloaded this task to what I thought was mullvad support.  Since i am
paying for this service it falls into their hands to fix it.

Again i thank you and will dl your code from github and if needed will let
you know if i have anything meaningful in the ways of modifications to
either extend the functionality or ... but it seems like you have
everything under control.

Thanks again for your time. It's unfortunate that mullvad is using
unreliable dns servers since they provide great services otherwise.

**Comment by oskaralmlov** [comment]
Allow me to fill in the blanks from the serverside of things.

On `us-lax-wg-202` we cannot resolve `www.baidu.com`:
```
oskaralmlov@us-lax-wg-202:~$ dig www.baidu.com
[...]
;; ->>HEADER<<- opcode: QUERY, status: SERVFAIL, id: 19987
[...]
```

Let's figure out which servers are authoritative (responsible) for `baidu.com`:
```
oskaralmlov@us-lax-wg-202:~$ dig baidu.com NS +short
ns2.baidu.com.
ns7.baidu.com.
dns.baidu.com.
ns3.baidu.com.
ns4.baidu.com.
```

Let's try resolving `www.baidu.com` by asking these servers directly:
```
oskaralmlov@us-lax-wg-202:~$ \
for hostname in $(dig baidu.com NS +short); do
> echo $hostname
> dig @$hostname www.baidu.com +short || echo "Timed out"
> done

ns4.baidu.com.
Timed out
ns2.baidu.com.
Timed out
ns3.baidu.com.
Timed out
ns7.baidu.com.
www.a.shifen.com.
```
It appears we can't reach the majority of the servers that are authoritative for this hostname.

Running the same task on a completely different server (`se-sto-wg-009`) yields very different results:
```
ns4.baidu.com.
www.a.shifen.com.
dns.baidu.com.
www.a.shifen.com.
ns2.baidu.com.
www.a.shifen.com.
ns3.baidu.com.
www.a.shifen.com.
ns7.baidu.com.
www.a.shifen.com.
```

Conclusion/Theorizing:
 * The authoritative servers for baidu.com appears to, from a DNS perspective, be configured correctly. 
 * Some of our relays cannot reach the authoritative servers for baidu.com. Or the response from the authoritative servers can't reach some of our relays. Either way the relay sends a query and does not get a response. 
 * Since the queries are leaving our relays as they should, we can't really do anything else. Someone or something is dropping our queries or the answers to our queries on the way. Speaking from experience this is most likely because there is some blocklist in use that is blocking traffic from known VPN IPs.

In order to get you the right support it's better to reach out to our support at `support@mullvad.net` since our support team does not have a presence on GitHub.

**Comment by slammpete** [comment]
Thanks for the testing. This has happened in the past with sites in China
using various vpn's or even trying to connect directly from my usa ip. I'm
not sure why china does this sporadically or without reason but during my
investigation last year i also found that it was on their end.

I am not sure how big the user base is for mullvad but i found when using a
new vpn things would work fine but when more users  started using the vpn
this would start to happen. It could be someone using mullvad maliciously
which is causing it.

I will contact mullvad support but i am pretty sure they won't be able to
help with this as it's on china's end.
